name: Automated Dataset Preprocessing and Merge

on:
  push:
    branches: [main]
    # =================================================================
    # === PERUBAHAN KUNCI: TAMBAHKAN FILTER 'PATHS' DI SINI =========
    # =================================================================
    # Workflow ini hanya akan berjalan jika ada perubahan pada file/folder di bawah ini
    paths:
      - "Rice_Image_Dataset/**" # Semua file di dalam dan di bawah folder Rice_Image_Dataset
      - "preprocessing/automate_TemaAnggara.py" # Jika skripnya diubah
      - ".github/workflows/preprocess_dataset.yml" # Jika workflownya sendiri diubah

  # Kita tetap pertahankan workflow_dispatch agar bisa dijalankan manual
  workflow_dispatch:

jobs:
  preprocess-and-automerge:
    name: Preprocess Dataset and Auto-Merge PR
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tqdm

      - name: Run Data Splitting Script
        run: python preprocessing/automate_TemaAnggara.py

      - name: Create Pull Request if changes detected
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: "ci: Automated dataset split"
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          branch: "update/processed-dataset"
          title: "[Automated] Update Processed Dataset"
          body: |
            This PR was auto-generated by a GitHub Action.
            It contains the latest version of the processed dataset. This PR will be auto-merged.
          delete-branch: true

      - name: Auto-merge the Pull Request
        if: steps.cpr.outputs.pull-request-number
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --merge --delete-branch
        env:
          GH_TOKEN: ${{ secrets.PAT }}
